# Site settings
title: eForms
email: eforms@tanglegence.com
description: An EU legislative open standard for publishing public procurement data
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://eforms.tanglegence.com" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
